/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as OrganizationsRouteImport } from './routes/organizations'
import { Route as GuideRouteImport } from './routes/guide'
import { Route as OrgSlugRouteRouteImport } from './routes/$orgSlug/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FTokenRouteImport } from './routes/f/$token'
import { Route as authVerifyEmailRouteImport } from './routes/(auth)/verify-email'
import { Route as authSignupRouteImport } from './routes/(auth)/signup'
import { Route as authOnboardingRouteImport } from './routes/(auth)/onboarding'
import { Route as authLoginRouteImport } from './routes/(auth)/login'
import { Route as OrgSlugAdminRouteImport } from './routes/$orgSlug/admin'
import { Route as OrgSlugAdminIndexRouteImport } from './routes/$orgSlug/admin/index'
import { Route as ApiV1WidgetRouteImport } from './routes/api/v1/widget'
import { Route as ApiV1FeedbacksRouteImport } from './routes/api/v1/feedbacks'
import { Route as ApiV1FeedbackRouteImport } from './routes/api/v1/feedback'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as OrgSlugAdminSettingsRouteImport } from './routes/$orgSlug/admin/settings'
import { Route as OrgSlugAdminFeedbacksRouteImport } from './routes/$orgSlug/admin/feedbacks'
import { Route as OrgSlugAdminProjectsIndexRouteImport } from './routes/$orgSlug/admin/projects/index'
import { Route as ApiV1TicketsTokenRouteImport } from './routes/api/v1/tickets.$token'
import { Route as ApiV1FeedbacksFeedbackIdRouteImport } from './routes/api/v1/feedbacks.$feedbackId'
import { Route as OrgSlugAdminProjectsProjectIdRouteImport } from './routes/$orgSlug/admin/projects/$projectId'
import { Route as ApiV1TicketsTokenRepliesRouteImport } from './routes/api/v1/tickets.$token.replies'
import { Route as ApiV1ProjectsProjectIdWidgetConfigRouteImport } from './routes/api/v1/projects.$projectId.widget-config'
import { Route as ApiV1FeedbacksFeedbackIdRepliesRouteImport } from './routes/api/v1/feedbacks.$feedbackId.replies'
import { Route as ApiV1FeedbacksFeedbackIdRepliesReplyIdRouteImport } from './routes/api/v1/feedbacks.$feedbackId.replies.$replyId'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizationsRoute = OrganizationsRouteImport.update({
  id: '/organizations',
  path: '/organizations',
  getParentRoute: () => rootRouteImport,
} as any)
const GuideRoute = GuideRouteImport.update({
  id: '/guide',
  path: '/guide',
  getParentRoute: () => rootRouteImport,
} as any)
const OrgSlugRouteRoute = OrgSlugRouteRouteImport.update({
  id: '/$orgSlug',
  path: '/$orgSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FTokenRoute = FTokenRouteImport.update({
  id: '/f/$token',
  path: '/f/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const authVerifyEmailRoute = authVerifyEmailRouteImport.update({
  id: '/(auth)/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignupRoute = authSignupRouteImport.update({
  id: '/(auth)/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const authOnboardingRoute = authOnboardingRouteImport.update({
  id: '/(auth)/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const authLoginRoute = authLoginRouteImport.update({
  id: '/(auth)/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const OrgSlugAdminRoute = OrgSlugAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => OrgSlugRouteRoute,
} as any)
const OrgSlugAdminIndexRoute = OrgSlugAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OrgSlugAdminRoute,
} as any)
const ApiV1WidgetRoute = ApiV1WidgetRouteImport.update({
  id: '/api/v1/widget',
  path: '/api/v1/widget',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1FeedbacksRoute = ApiV1FeedbacksRouteImport.update({
  id: '/api/v1/feedbacks',
  path: '/api/v1/feedbacks',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1FeedbackRoute = ApiV1FeedbackRouteImport.update({
  id: '/api/v1/feedback',
  path: '/api/v1/feedback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const OrgSlugAdminSettingsRoute = OrgSlugAdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => OrgSlugAdminRoute,
} as any)
const OrgSlugAdminFeedbacksRoute = OrgSlugAdminFeedbacksRouteImport.update({
  id: '/feedbacks',
  path: '/feedbacks',
  getParentRoute: () => OrgSlugAdminRoute,
} as any)
const OrgSlugAdminProjectsIndexRoute =
  OrgSlugAdminProjectsIndexRouteImport.update({
    id: '/projects/',
    path: '/projects/',
    getParentRoute: () => OrgSlugAdminRoute,
  } as any)
const ApiV1TicketsTokenRoute = ApiV1TicketsTokenRouteImport.update({
  id: '/api/v1/tickets/$token',
  path: '/api/v1/tickets/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1FeedbacksFeedbackIdRoute =
  ApiV1FeedbacksFeedbackIdRouteImport.update({
    id: '/$feedbackId',
    path: '/$feedbackId',
    getParentRoute: () => ApiV1FeedbacksRoute,
  } as any)
const OrgSlugAdminProjectsProjectIdRoute =
  OrgSlugAdminProjectsProjectIdRouteImport.update({
    id: '/projects/$projectId',
    path: '/projects/$projectId',
    getParentRoute: () => OrgSlugAdminRoute,
  } as any)
const ApiV1TicketsTokenRepliesRoute =
  ApiV1TicketsTokenRepliesRouteImport.update({
    id: '/replies',
    path: '/replies',
    getParentRoute: () => ApiV1TicketsTokenRoute,
  } as any)
const ApiV1ProjectsProjectIdWidgetConfigRoute =
  ApiV1ProjectsProjectIdWidgetConfigRouteImport.update({
    id: '/api/v1/projects/$projectId/widget-config',
    path: '/api/v1/projects/$projectId/widget-config',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiV1FeedbacksFeedbackIdRepliesRoute =
  ApiV1FeedbacksFeedbackIdRepliesRouteImport.update({
    id: '/replies',
    path: '/replies',
    getParentRoute: () => ApiV1FeedbacksFeedbackIdRoute,
  } as any)
const ApiV1FeedbacksFeedbackIdRepliesReplyIdRoute =
  ApiV1FeedbacksFeedbackIdRepliesReplyIdRouteImport.update({
    id: '/$replyId',
    path: '/$replyId',
    getParentRoute: () => ApiV1FeedbacksFeedbackIdRepliesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$orgSlug': typeof OrgSlugRouteRouteWithChildren
  '/guide': typeof GuideRoute
  '/organizations': typeof OrganizationsRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/$orgSlug/admin': typeof OrgSlugAdminRouteWithChildren
  '/login': typeof authLoginRoute
  '/onboarding': typeof authOnboardingRoute
  '/signup': typeof authSignupRoute
  '/verify-email': typeof authVerifyEmailRoute
  '/f/$token': typeof FTokenRoute
  '/$orgSlug/admin/feedbacks': typeof OrgSlugAdminFeedbacksRoute
  '/$orgSlug/admin/settings': typeof OrgSlugAdminSettingsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/v1/feedback': typeof ApiV1FeedbackRoute
  '/api/v1/feedbacks': typeof ApiV1FeedbacksRouteWithChildren
  '/api/v1/widget': typeof ApiV1WidgetRoute
  '/$orgSlug/admin/': typeof OrgSlugAdminIndexRoute
  '/$orgSlug/admin/projects/$projectId': typeof OrgSlugAdminProjectsProjectIdRoute
  '/api/v1/feedbacks/$feedbackId': typeof ApiV1FeedbacksFeedbackIdRouteWithChildren
  '/api/v1/tickets/$token': typeof ApiV1TicketsTokenRouteWithChildren
  '/$orgSlug/admin/projects': typeof OrgSlugAdminProjectsIndexRoute
  '/api/v1/feedbacks/$feedbackId/replies': typeof ApiV1FeedbacksFeedbackIdRepliesRouteWithChildren
  '/api/v1/projects/$projectId/widget-config': typeof ApiV1ProjectsProjectIdWidgetConfigRoute
  '/api/v1/tickets/$token/replies': typeof ApiV1TicketsTokenRepliesRoute
  '/api/v1/feedbacks/$feedbackId/replies/$replyId': typeof ApiV1FeedbacksFeedbackIdRepliesReplyIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$orgSlug': typeof OrgSlugRouteRouteWithChildren
  '/guide': typeof GuideRoute
  '/organizations': typeof OrganizationsRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/login': typeof authLoginRoute
  '/onboarding': typeof authOnboardingRoute
  '/signup': typeof authSignupRoute
  '/verify-email': typeof authVerifyEmailRoute
  '/f/$token': typeof FTokenRoute
  '/$orgSlug/admin/feedbacks': typeof OrgSlugAdminFeedbacksRoute
  '/$orgSlug/admin/settings': typeof OrgSlugAdminSettingsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/v1/feedback': typeof ApiV1FeedbackRoute
  '/api/v1/feedbacks': typeof ApiV1FeedbacksRouteWithChildren
  '/api/v1/widget': typeof ApiV1WidgetRoute
  '/$orgSlug/admin': typeof OrgSlugAdminIndexRoute
  '/$orgSlug/admin/projects/$projectId': typeof OrgSlugAdminProjectsProjectIdRoute
  '/api/v1/feedbacks/$feedbackId': typeof ApiV1FeedbacksFeedbackIdRouteWithChildren
  '/api/v1/tickets/$token': typeof ApiV1TicketsTokenRouteWithChildren
  '/$orgSlug/admin/projects': typeof OrgSlugAdminProjectsIndexRoute
  '/api/v1/feedbacks/$feedbackId/replies': typeof ApiV1FeedbacksFeedbackIdRepliesRouteWithChildren
  '/api/v1/projects/$projectId/widget-config': typeof ApiV1ProjectsProjectIdWidgetConfigRoute
  '/api/v1/tickets/$token/replies': typeof ApiV1TicketsTokenRepliesRoute
  '/api/v1/feedbacks/$feedbackId/replies/$replyId': typeof ApiV1FeedbacksFeedbackIdRepliesReplyIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$orgSlug': typeof OrgSlugRouteRouteWithChildren
  '/guide': typeof GuideRoute
  '/organizations': typeof OrganizationsRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/$orgSlug/admin': typeof OrgSlugAdminRouteWithChildren
  '/(auth)/login': typeof authLoginRoute
  '/(auth)/onboarding': typeof authOnboardingRoute
  '/(auth)/signup': typeof authSignupRoute
  '/(auth)/verify-email': typeof authVerifyEmailRoute
  '/f/$token': typeof FTokenRoute
  '/$orgSlug/admin/feedbacks': typeof OrgSlugAdminFeedbacksRoute
  '/$orgSlug/admin/settings': typeof OrgSlugAdminSettingsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/v1/feedback': typeof ApiV1FeedbackRoute
  '/api/v1/feedbacks': typeof ApiV1FeedbacksRouteWithChildren
  '/api/v1/widget': typeof ApiV1WidgetRoute
  '/$orgSlug/admin/': typeof OrgSlugAdminIndexRoute
  '/$orgSlug/admin/projects/$projectId': typeof OrgSlugAdminProjectsProjectIdRoute
  '/api/v1/feedbacks/$feedbackId': typeof ApiV1FeedbacksFeedbackIdRouteWithChildren
  '/api/v1/tickets/$token': typeof ApiV1TicketsTokenRouteWithChildren
  '/$orgSlug/admin/projects/': typeof OrgSlugAdminProjectsIndexRoute
  '/api/v1/feedbacks/$feedbackId/replies': typeof ApiV1FeedbacksFeedbackIdRepliesRouteWithChildren
  '/api/v1/projects/$projectId/widget-config': typeof ApiV1ProjectsProjectIdWidgetConfigRoute
  '/api/v1/tickets/$token/replies': typeof ApiV1TicketsTokenRepliesRoute
  '/api/v1/feedbacks/$feedbackId/replies/$replyId': typeof ApiV1FeedbacksFeedbackIdRepliesReplyIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$orgSlug'
    | '/guide'
    | '/organizations'
    | '/privacy'
    | '/terms'
    | '/$orgSlug/admin'
    | '/login'
    | '/onboarding'
    | '/signup'
    | '/verify-email'
    | '/f/$token'
    | '/$orgSlug/admin/feedbacks'
    | '/$orgSlug/admin/settings'
    | '/api/auth/$'
    | '/api/v1/feedback'
    | '/api/v1/feedbacks'
    | '/api/v1/widget'
    | '/$orgSlug/admin/'
    | '/$orgSlug/admin/projects/$projectId'
    | '/api/v1/feedbacks/$feedbackId'
    | '/api/v1/tickets/$token'
    | '/$orgSlug/admin/projects'
    | '/api/v1/feedbacks/$feedbackId/replies'
    | '/api/v1/projects/$projectId/widget-config'
    | '/api/v1/tickets/$token/replies'
    | '/api/v1/feedbacks/$feedbackId/replies/$replyId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$orgSlug'
    | '/guide'
    | '/organizations'
    | '/privacy'
    | '/terms'
    | '/login'
    | '/onboarding'
    | '/signup'
    | '/verify-email'
    | '/f/$token'
    | '/$orgSlug/admin/feedbacks'
    | '/$orgSlug/admin/settings'
    | '/api/auth/$'
    | '/api/v1/feedback'
    | '/api/v1/feedbacks'
    | '/api/v1/widget'
    | '/$orgSlug/admin'
    | '/$orgSlug/admin/projects/$projectId'
    | '/api/v1/feedbacks/$feedbackId'
    | '/api/v1/tickets/$token'
    | '/$orgSlug/admin/projects'
    | '/api/v1/feedbacks/$feedbackId/replies'
    | '/api/v1/projects/$projectId/widget-config'
    | '/api/v1/tickets/$token/replies'
    | '/api/v1/feedbacks/$feedbackId/replies/$replyId'
  id:
    | '__root__'
    | '/'
    | '/$orgSlug'
    | '/guide'
    | '/organizations'
    | '/privacy'
    | '/terms'
    | '/$orgSlug/admin'
    | '/(auth)/login'
    | '/(auth)/onboarding'
    | '/(auth)/signup'
    | '/(auth)/verify-email'
    | '/f/$token'
    | '/$orgSlug/admin/feedbacks'
    | '/$orgSlug/admin/settings'
    | '/api/auth/$'
    | '/api/v1/feedback'
    | '/api/v1/feedbacks'
    | '/api/v1/widget'
    | '/$orgSlug/admin/'
    | '/$orgSlug/admin/projects/$projectId'
    | '/api/v1/feedbacks/$feedbackId'
    | '/api/v1/tickets/$token'
    | '/$orgSlug/admin/projects/'
    | '/api/v1/feedbacks/$feedbackId/replies'
    | '/api/v1/projects/$projectId/widget-config'
    | '/api/v1/tickets/$token/replies'
    | '/api/v1/feedbacks/$feedbackId/replies/$replyId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  OrgSlugRouteRoute: typeof OrgSlugRouteRouteWithChildren
  GuideRoute: typeof GuideRoute
  OrganizationsRoute: typeof OrganizationsRoute
  PrivacyRoute: typeof PrivacyRoute
  TermsRoute: typeof TermsRoute
  authLoginRoute: typeof authLoginRoute
  authOnboardingRoute: typeof authOnboardingRoute
  authSignupRoute: typeof authSignupRoute
  authVerifyEmailRoute: typeof authVerifyEmailRoute
  FTokenRoute: typeof FTokenRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiV1FeedbackRoute: typeof ApiV1FeedbackRoute
  ApiV1FeedbacksRoute: typeof ApiV1FeedbacksRouteWithChildren
  ApiV1WidgetRoute: typeof ApiV1WidgetRoute
  ApiV1TicketsTokenRoute: typeof ApiV1TicketsTokenRouteWithChildren
  ApiV1ProjectsProjectIdWidgetConfigRoute: typeof ApiV1ProjectsProjectIdWidgetConfigRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organizations': {
      id: '/organizations'
      path: '/organizations'
      fullPath: '/organizations'
      preLoaderRoute: typeof OrganizationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guide': {
      id: '/guide'
      path: '/guide'
      fullPath: '/guide'
      preLoaderRoute: typeof GuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$orgSlug': {
      id: '/$orgSlug'
      path: '/$orgSlug'
      fullPath: '/$orgSlug'
      preLoaderRoute: typeof OrgSlugRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/f/$token': {
      id: '/f/$token'
      path: '/f/$token'
      fullPath: '/f/$token'
      preLoaderRoute: typeof FTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/verify-email': {
      id: '/(auth)/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof authVerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/signup': {
      id: '/(auth)/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof authSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/onboarding': {
      id: '/(auth)/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof authOnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/login': {
      id: '/(auth)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$orgSlug/admin': {
      id: '/$orgSlug/admin'
      path: '/admin'
      fullPath: '/$orgSlug/admin'
      preLoaderRoute: typeof OrgSlugAdminRouteImport
      parentRoute: typeof OrgSlugRouteRoute
    }
    '/$orgSlug/admin/': {
      id: '/$orgSlug/admin/'
      path: '/'
      fullPath: '/$orgSlug/admin/'
      preLoaderRoute: typeof OrgSlugAdminIndexRouteImport
      parentRoute: typeof OrgSlugAdminRoute
    }
    '/api/v1/widget': {
      id: '/api/v1/widget'
      path: '/api/v1/widget'
      fullPath: '/api/v1/widget'
      preLoaderRoute: typeof ApiV1WidgetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/feedbacks': {
      id: '/api/v1/feedbacks'
      path: '/api/v1/feedbacks'
      fullPath: '/api/v1/feedbacks'
      preLoaderRoute: typeof ApiV1FeedbacksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/feedback': {
      id: '/api/v1/feedback'
      path: '/api/v1/feedback'
      fullPath: '/api/v1/feedback'
      preLoaderRoute: typeof ApiV1FeedbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$orgSlug/admin/settings': {
      id: '/$orgSlug/admin/settings'
      path: '/settings'
      fullPath: '/$orgSlug/admin/settings'
      preLoaderRoute: typeof OrgSlugAdminSettingsRouteImport
      parentRoute: typeof OrgSlugAdminRoute
    }
    '/$orgSlug/admin/feedbacks': {
      id: '/$orgSlug/admin/feedbacks'
      path: '/feedbacks'
      fullPath: '/$orgSlug/admin/feedbacks'
      preLoaderRoute: typeof OrgSlugAdminFeedbacksRouteImport
      parentRoute: typeof OrgSlugAdminRoute
    }
    '/$orgSlug/admin/projects/': {
      id: '/$orgSlug/admin/projects/'
      path: '/projects'
      fullPath: '/$orgSlug/admin/projects'
      preLoaderRoute: typeof OrgSlugAdminProjectsIndexRouteImport
      parentRoute: typeof OrgSlugAdminRoute
    }
    '/api/v1/tickets/$token': {
      id: '/api/v1/tickets/$token'
      path: '/api/v1/tickets/$token'
      fullPath: '/api/v1/tickets/$token'
      preLoaderRoute: typeof ApiV1TicketsTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/feedbacks/$feedbackId': {
      id: '/api/v1/feedbacks/$feedbackId'
      path: '/$feedbackId'
      fullPath: '/api/v1/feedbacks/$feedbackId'
      preLoaderRoute: typeof ApiV1FeedbacksFeedbackIdRouteImport
      parentRoute: typeof ApiV1FeedbacksRoute
    }
    '/$orgSlug/admin/projects/$projectId': {
      id: '/$orgSlug/admin/projects/$projectId'
      path: '/projects/$projectId'
      fullPath: '/$orgSlug/admin/projects/$projectId'
      preLoaderRoute: typeof OrgSlugAdminProjectsProjectIdRouteImport
      parentRoute: typeof OrgSlugAdminRoute
    }
    '/api/v1/tickets/$token/replies': {
      id: '/api/v1/tickets/$token/replies'
      path: '/replies'
      fullPath: '/api/v1/tickets/$token/replies'
      preLoaderRoute: typeof ApiV1TicketsTokenRepliesRouteImport
      parentRoute: typeof ApiV1TicketsTokenRoute
    }
    '/api/v1/projects/$projectId/widget-config': {
      id: '/api/v1/projects/$projectId/widget-config'
      path: '/api/v1/projects/$projectId/widget-config'
      fullPath: '/api/v1/projects/$projectId/widget-config'
      preLoaderRoute: typeof ApiV1ProjectsProjectIdWidgetConfigRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/feedbacks/$feedbackId/replies': {
      id: '/api/v1/feedbacks/$feedbackId/replies'
      path: '/replies'
      fullPath: '/api/v1/feedbacks/$feedbackId/replies'
      preLoaderRoute: typeof ApiV1FeedbacksFeedbackIdRepliesRouteImport
      parentRoute: typeof ApiV1FeedbacksFeedbackIdRoute
    }
    '/api/v1/feedbacks/$feedbackId/replies/$replyId': {
      id: '/api/v1/feedbacks/$feedbackId/replies/$replyId'
      path: '/$replyId'
      fullPath: '/api/v1/feedbacks/$feedbackId/replies/$replyId'
      preLoaderRoute: typeof ApiV1FeedbacksFeedbackIdRepliesReplyIdRouteImport
      parentRoute: typeof ApiV1FeedbacksFeedbackIdRepliesRoute
    }
  }
}

interface OrgSlugAdminRouteChildren {
  OrgSlugAdminFeedbacksRoute: typeof OrgSlugAdminFeedbacksRoute
  OrgSlugAdminSettingsRoute: typeof OrgSlugAdminSettingsRoute
  OrgSlugAdminIndexRoute: typeof OrgSlugAdminIndexRoute
  OrgSlugAdminProjectsProjectIdRoute: typeof OrgSlugAdminProjectsProjectIdRoute
  OrgSlugAdminProjectsIndexRoute: typeof OrgSlugAdminProjectsIndexRoute
}

const OrgSlugAdminRouteChildren: OrgSlugAdminRouteChildren = {
  OrgSlugAdminFeedbacksRoute: OrgSlugAdminFeedbacksRoute,
  OrgSlugAdminSettingsRoute: OrgSlugAdminSettingsRoute,
  OrgSlugAdminIndexRoute: OrgSlugAdminIndexRoute,
  OrgSlugAdminProjectsProjectIdRoute: OrgSlugAdminProjectsProjectIdRoute,
  OrgSlugAdminProjectsIndexRoute: OrgSlugAdminProjectsIndexRoute,
}

const OrgSlugAdminRouteWithChildren = OrgSlugAdminRoute._addFileChildren(
  OrgSlugAdminRouteChildren,
)

interface OrgSlugRouteRouteChildren {
  OrgSlugAdminRoute: typeof OrgSlugAdminRouteWithChildren
}

const OrgSlugRouteRouteChildren: OrgSlugRouteRouteChildren = {
  OrgSlugAdminRoute: OrgSlugAdminRouteWithChildren,
}

const OrgSlugRouteRouteWithChildren = OrgSlugRouteRoute._addFileChildren(
  OrgSlugRouteRouteChildren,
)

interface ApiV1FeedbacksFeedbackIdRepliesRouteChildren {
  ApiV1FeedbacksFeedbackIdRepliesReplyIdRoute: typeof ApiV1FeedbacksFeedbackIdRepliesReplyIdRoute
}

const ApiV1FeedbacksFeedbackIdRepliesRouteChildren: ApiV1FeedbacksFeedbackIdRepliesRouteChildren =
  {
    ApiV1FeedbacksFeedbackIdRepliesReplyIdRoute:
      ApiV1FeedbacksFeedbackIdRepliesReplyIdRoute,
  }

const ApiV1FeedbacksFeedbackIdRepliesRouteWithChildren =
  ApiV1FeedbacksFeedbackIdRepliesRoute._addFileChildren(
    ApiV1FeedbacksFeedbackIdRepliesRouteChildren,
  )

interface ApiV1FeedbacksFeedbackIdRouteChildren {
  ApiV1FeedbacksFeedbackIdRepliesRoute: typeof ApiV1FeedbacksFeedbackIdRepliesRouteWithChildren
}

const ApiV1FeedbacksFeedbackIdRouteChildren: ApiV1FeedbacksFeedbackIdRouteChildren =
  {
    ApiV1FeedbacksFeedbackIdRepliesRoute:
      ApiV1FeedbacksFeedbackIdRepliesRouteWithChildren,
  }

const ApiV1FeedbacksFeedbackIdRouteWithChildren =
  ApiV1FeedbacksFeedbackIdRoute._addFileChildren(
    ApiV1FeedbacksFeedbackIdRouteChildren,
  )

interface ApiV1FeedbacksRouteChildren {
  ApiV1FeedbacksFeedbackIdRoute: typeof ApiV1FeedbacksFeedbackIdRouteWithChildren
}

const ApiV1FeedbacksRouteChildren: ApiV1FeedbacksRouteChildren = {
  ApiV1FeedbacksFeedbackIdRoute: ApiV1FeedbacksFeedbackIdRouteWithChildren,
}

const ApiV1FeedbacksRouteWithChildren = ApiV1FeedbacksRoute._addFileChildren(
  ApiV1FeedbacksRouteChildren,
)

interface ApiV1TicketsTokenRouteChildren {
  ApiV1TicketsTokenRepliesRoute: typeof ApiV1TicketsTokenRepliesRoute
}

const ApiV1TicketsTokenRouteChildren: ApiV1TicketsTokenRouteChildren = {
  ApiV1TicketsTokenRepliesRoute: ApiV1TicketsTokenRepliesRoute,
}

const ApiV1TicketsTokenRouteWithChildren =
  ApiV1TicketsTokenRoute._addFileChildren(ApiV1TicketsTokenRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  OrgSlugRouteRoute: OrgSlugRouteRouteWithChildren,
  GuideRoute: GuideRoute,
  OrganizationsRoute: OrganizationsRoute,
  PrivacyRoute: PrivacyRoute,
  TermsRoute: TermsRoute,
  authLoginRoute: authLoginRoute,
  authOnboardingRoute: authOnboardingRoute,
  authSignupRoute: authSignupRoute,
  authVerifyEmailRoute: authVerifyEmailRoute,
  FTokenRoute: FTokenRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiV1FeedbackRoute: ApiV1FeedbackRoute,
  ApiV1FeedbacksRoute: ApiV1FeedbacksRouteWithChildren,
  ApiV1WidgetRoute: ApiV1WidgetRoute,
  ApiV1TicketsTokenRoute: ApiV1TicketsTokenRouteWithChildren,
  ApiV1ProjectsProjectIdWidgetConfigRoute:
    ApiV1ProjectsProjectIdWidgetConfigRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
