name: Feature Request
description: 새로운 기능 요청
title: "[Feature] "
labels: ["type: feature"]
body:
  - type: dropdown
    id: scope
    attributes:
      label: Scope
      description: 어떤 패키지/앱에 관련된 기능인가요?
      options:
        - web (apps/web)
        - cdn (apps/cdn)
        - core (packages/core)
        - database (packages/database)
        - 기타
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: 우선순위를 선택해주세요
      options:
        - high
        - medium
        - low
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: 설명
      description: 구현하고자 하는 기능을 설명해주세요
      placeholder: 어떤 기능이 필요한가요?
    validations:
      required: true

  - type: textarea
    id: tasks
    attributes:
      label: Tasks
      description: 세부 작업 목록 (선택)
      placeholder: |
        - [ ] Task 1
        - [ ] Task 2
    validations:
      required: false

  - type: textarea
    id: notes
    attributes:
      label: 참고사항
      description: 추가 정보나 참고할 내용
    validations:
      required: false
